"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const categories_routes_1 = require("./categories.routes");
const Specifications_routes_1 = require("./Specifications.routes");
const users_routes_1 = require("./users.routes");
const router = (0, express_1.Router)();
exports.router = router;
router.use("/categories", categories_routes_1.categoriesRoutes);
router.use("/specifications", Specifications_routes_1.specificationsRoutes);
router.use("/users", users_routes_1.usersRoutes);
