name: CI

on: 
  push:
    branches: [main]
    
  workflow_dispatch:
    
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        
        - name: setup Nodejs
          uses:  actions/setup-node@v2
          with:
            node-version: 18.14.2
            
        - name: Instal Dependencies
          run: yarn
          
        - name: Build
          run: yarn build
          
        
    
